import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import NavBar from "@/components/NavBar";
import MapBox from "@/components/MapBox";
import SignInView from "@/components/views/SingInView";

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        figtree.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <div className="fixed inset-0 z-0">
          <MapBox />
        </div>
        <main className="relative z-10 h-full w-full pointer-events-none ">
          {children}

          {/* sign in component checks for changes to the URL, upon page refresh it mounts if reqAuth = true*/}
          <SignInView />
          {modal}
        </main>
        <NavBar />
      </body>
    </html>
  );
}
