import type { Metadata } from "next";
import PlayerLayoutWrapper from "@/app/(player)/PlayerLayoutWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="">
      <PlayerLayoutWrapper children={children} />
    </div>
  );
}
