import type { Metadata } from "next";
import PlayerWrapper from "@/components/layoutWrappers/PlayerWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <PlayerWrapper children={children} />
    </div>
  );
}
