create type "public"."age_group" as enum ('18_29', '30_39', '40_49', '50_plus', 'any');

create type "public"."gender" as enum ('male', 'female', 'prefer_not_to_say', 'any');

create type "public"."skill_level" as enum ('beginner', 'intermediate', 'advanced', 'professional', 'any');

create type "public"."sport" as enum ('football', 'basketball', 'volleyball', 'tennis', 'badminton');

drop policy "Enable read access for all users" on "public"."Player";

drop policy "Enable update for users based on user_id" on "public"."Player";

revoke delete on table "public"."Player" from "anon";

revoke insert on table "public"."Player" from "anon";

revoke references on table "public"."Player" from "anon";

revoke select on table "public"."Player" from "anon";

revoke trigger on table "public"."Player" from "anon";

revoke truncate on table "public"."Player" from "anon";

revoke update on table "public"."Player" from "anon";

revoke delete on table "public"."Player" from "authenticated";

revoke insert on table "public"."Player" from "authenticated";

revoke references on table "public"."Player" from "authenticated";

revoke select on table "public"."Player" from "authenticated";

revoke trigger on table "public"."Player" from "authenticated";

revoke truncate on table "public"."Player" from "authenticated";

revoke update on table "public"."Player" from "authenticated";

revoke delete on table "public"."Player" from "service_role";

revoke insert on table "public"."Player" from "service_role";

revoke references on table "public"."Player" from "service_role";

revoke select on table "public"."Player" from "service_role";

revoke trigger on table "public"."Player" from "service_role";

revoke truncate on table "public"."Player" from "service_role";

revoke update on table "public"."Player" from "service_role";

alter table "public"."Player" drop constraint "Player_id_fkey";

alter table "public"."Player" drop constraint "Player_username_key";

alter table "public"."Player" drop constraint "Player_pkey";

drop index if exists "public"."Player_pkey";

drop index if exists "public"."Player_username_key";

drop table "public"."Player";


  create table "public"."Announcement" (
    "announcement_id" uuid not null default gen_random_uuid(),
    "owner" uuid not null,
    "sport" public.sport not null,
    "age" public.age_group not null,
    "gender" public.gender not null,
    "skill_level" public.skill_level not null,
    "description" text not null,
    "max_players" smallint not null,
    "created_at" timestamp with time zone not null default now(),
    "location_name" text not null,
    "latitude" double precision not null,
    "longitude" double precision not null,
    "min_players" smallint not null
      );


alter table "public"."Announcement" enable row level security;


  create table "public"."Announcement_members" (
    "id" bigint generated by default as identity not null,
    "announcement" uuid not null,
    "player" uuid not null
      );


alter table "public"."Announcement_members" enable row level security;


  create table "public"."Players" (
    "id" uuid not null,
    "first_name" text not null,
    "surname" text,
    "username" text,
    "avatar_url" text,
    "bio" text,
    "gender" text,
    "birth_year" smallint,
    "home" text,
    "is_onboarded" boolean not null default false
      );


alter table "public"."Players" enable row level security;


  create table "public"."Users" (
    "id" uuid not null default gen_random_uuid(),
    "account_type" text
      );


alter table "public"."Users" enable row level security;

CREATE UNIQUE INDEX "Announcement_pkey" ON public."Announcement" USING btree (announcement_id);

CREATE UNIQUE INDEX annouuncement_members_pkey ON public."Announcement_members" USING btree (id);

CREATE UNIQUE INDEX unique_announcement_player ON public."Announcement_members" USING btree (announcement, player);

CREATE UNIQUE INDEX user_pkey ON public."Users" USING btree (id);

CREATE UNIQUE INDEX "Player_pkey" ON public."Players" USING btree (id);

CREATE UNIQUE INDEX "Player_username_key" ON public."Players" USING btree (username);

alter table "public"."Announcement" add constraint "Announcement_pkey" PRIMARY KEY using index "Announcement_pkey";

alter table "public"."Announcement_members" add constraint "annouuncement_members_pkey" PRIMARY KEY using index "annouuncement_members_pkey";

alter table "public"."Players" add constraint "Player_pkey" PRIMARY KEY using index "Player_pkey";

alter table "public"."Users" add constraint "user_pkey" PRIMARY KEY using index "user_pkey";

alter table "public"."Announcement" add constraint "Announcement_owner_fkey" FOREIGN KEY (owner) REFERENCES public."Players"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Announcement" validate constraint "Announcement_owner_fkey";

alter table "public"."Announcement_members" add constraint "annouuncement_members_announcement_fkey" FOREIGN KEY (announcement) REFERENCES public."Announcement"(announcement_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Announcement_members" validate constraint "annouuncement_members_announcement_fkey";

alter table "public"."Announcement_members" add constraint "annouuncement_members_player_fkey" FOREIGN KEY (player) REFERENCES public."Players"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Announcement_members" validate constraint "annouuncement_members_player_fkey";

alter table "public"."Players" add constraint "Player_username_key" UNIQUE using index "Player_username_key";

alter table "public"."Players" add constraint "Players_id_fkey" FOREIGN KEY (id) REFERENCES public."Users"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Players" validate constraint "Players_id_fkey";

alter table "public"."Users" add constraint "user_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Users" validate constraint "user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user_signup()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_catalog'
AS $function$BEGIN
  INSERT INTO public."Users" (id, account_type)
  VALUES (new.id, NULL);
  RETURN new;
END;$function$
;

grant delete on table "public"."Announcement" to "anon";

grant insert on table "public"."Announcement" to "anon";

grant references on table "public"."Announcement" to "anon";

grant select on table "public"."Announcement" to "anon";

grant trigger on table "public"."Announcement" to "anon";

grant truncate on table "public"."Announcement" to "anon";

grant update on table "public"."Announcement" to "anon";

grant delete on table "public"."Announcement" to "authenticated";

grant insert on table "public"."Announcement" to "authenticated";

grant references on table "public"."Announcement" to "authenticated";

grant select on table "public"."Announcement" to "authenticated";

grant trigger on table "public"."Announcement" to "authenticated";

grant truncate on table "public"."Announcement" to "authenticated";

grant update on table "public"."Announcement" to "authenticated";

grant delete on table "public"."Announcement" to "service_role";

grant insert on table "public"."Announcement" to "service_role";

grant references on table "public"."Announcement" to "service_role";

grant select on table "public"."Announcement" to "service_role";

grant trigger on table "public"."Announcement" to "service_role";

grant truncate on table "public"."Announcement" to "service_role";

grant update on table "public"."Announcement" to "service_role";

grant delete on table "public"."Announcement_members" to "anon";

grant insert on table "public"."Announcement_members" to "anon";

grant references on table "public"."Announcement_members" to "anon";

grant select on table "public"."Announcement_members" to "anon";

grant trigger on table "public"."Announcement_members" to "anon";

grant truncate on table "public"."Announcement_members" to "anon";

grant update on table "public"."Announcement_members" to "anon";

grant delete on table "public"."Announcement_members" to "authenticated";

grant insert on table "public"."Announcement_members" to "authenticated";

grant references on table "public"."Announcement_members" to "authenticated";

grant select on table "public"."Announcement_members" to "authenticated";

grant trigger on table "public"."Announcement_members" to "authenticated";

grant truncate on table "public"."Announcement_members" to "authenticated";

grant update on table "public"."Announcement_members" to "authenticated";

grant delete on table "public"."Announcement_members" to "service_role";

grant insert on table "public"."Announcement_members" to "service_role";

grant references on table "public"."Announcement_members" to "service_role";

grant select on table "public"."Announcement_members" to "service_role";

grant trigger on table "public"."Announcement_members" to "service_role";

grant truncate on table "public"."Announcement_members" to "service_role";

grant update on table "public"."Announcement_members" to "service_role";

grant delete on table "public"."Players" to "anon";

grant insert on table "public"."Players" to "anon";

grant references on table "public"."Players" to "anon";

grant select on table "public"."Players" to "anon";

grant trigger on table "public"."Players" to "anon";

grant truncate on table "public"."Players" to "anon";

grant update on table "public"."Players" to "anon";

grant delete on table "public"."Players" to "authenticated";

grant insert on table "public"."Players" to "authenticated";

grant references on table "public"."Players" to "authenticated";

grant select on table "public"."Players" to "authenticated";

grant trigger on table "public"."Players" to "authenticated";

grant truncate on table "public"."Players" to "authenticated";

grant update on table "public"."Players" to "authenticated";

grant delete on table "public"."Players" to "service_role";

grant insert on table "public"."Players" to "service_role";

grant references on table "public"."Players" to "service_role";

grant select on table "public"."Players" to "service_role";

grant trigger on table "public"."Players" to "service_role";

grant truncate on table "public"."Players" to "service_role";

grant update on table "public"."Players" to "service_role";

grant delete on table "public"."Users" to "anon";

grant insert on table "public"."Users" to "anon";

grant references on table "public"."Users" to "anon";

grant select on table "public"."Users" to "anon";

grant trigger on table "public"."Users" to "anon";

grant truncate on table "public"."Users" to "anon";

grant update on table "public"."Users" to "anon";

grant delete on table "public"."Users" to "authenticated";

grant insert on table "public"."Users" to "authenticated";

grant references on table "public"."Users" to "authenticated";

grant select on table "public"."Users" to "authenticated";

grant trigger on table "public"."Users" to "authenticated";

grant truncate on table "public"."Users" to "authenticated";

grant update on table "public"."Users" to "authenticated";

grant delete on table "public"."Users" to "service_role";

grant insert on table "public"."Users" to "service_role";

grant references on table "public"."Users" to "service_role";

grant select on table "public"."Users" to "service_role";

grant trigger on table "public"."Users" to "service_role";

grant truncate on table "public"."Users" to "service_role";

grant update on table "public"."Users" to "service_role";


  create policy "Enable delete for users based on user_id"
  on "public"."Announcement"
  as permissive
  for delete
  to public
using ((( SELECT auth.uid() AS uid) = owner));



  create policy "Enable read access for all users"
  on "public"."Announcement"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update for users based on user_id"
  on "public"."Announcement"
  as permissive
  for update
  to public
using ((( SELECT auth.uid() AS uid) = owner))
with check ((( SELECT auth.uid() AS uid) = owner));



  create policy "Enable read access for all users"
  on "public"."Players"
  as permissive
  for select
  to public
using (true);



  create policy "Enable update for users based on user_id"
  on "public"."Players"
  as permissive
  for update
  to public
using ((( SELECT auth.uid() AS uid) = id))
with check ((( SELECT auth.uid() AS uid) = id));



  create policy "Enable read access for owner"
  on "public"."Users"
  as permissive
  for select
  to authenticated
using ((auth.uid() = id));


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user_signup();


